SSL_TLS Post
michaelkochub/michaelkochub.github.io pull request #1
Opened 2018-01-08 05:35 UTC by mckornfield

2018-01-08 05:37 UTC, mckornfield commented
@michaelkochub Would like your initial feedback :) Any and all criticisms are welcome. I also know the few code snippets I have are off (tabs vs. spaces grr)

2018-01-15 23:35 UTC, michaelkochub requested changes
Halfway done with my review, looks pretty good so far.

2018-01-15 23:35 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +You might be aware of what it is, but could you explain Secure Socket Layer/ Transport Layer Security to a laymen? Can you picture in your mind what is happening when you type https://google.com into
to a **layman**

2018-01-15 23:35 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +title_stub: ssl
add something like `contributor: [your name]` to the yaml frontmatter... [kochub.com](http://kochub.com) is all about bestowing proper attribution

2018-01-15 23:35 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +Back in the Netscape days of yore, the first secured traffic was established by SSL v1. It was never released to the public, but soon after v2 was released. There were major issues with v2 that lead
Might be good to add a period, so `[More info here][TLS_vs_SSL].`

2018-01-15 23:35 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +An overly simplified explanation of asymmetric encryption is a way of encrypting something that makes it very difficult to decrypt unless you have certain keys. Brute forcing of this type can take an
Nice link 👍🏼

2018-01-15 23:35 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +Bill has just moved to a new address and wants to send Ted a letter. However, he is worried that evil-doers will intercept the letter and could possibly break any sort of encryption if he used some s
Perhaps rephrase the second sentence, using the word `sort` in adjacent clauses.

2018-01-15 23:35 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +Once it arrives on Ted's doorstep, he will be able to unlock his own lock and have access to the letter, which tells Ted that he is 'totally awesome' and 'far out'. He also now has a lock that he can
Could put the quotes in _italics_ too.

2018-01-16 02:33 UTC, michaelkochub requested changes

2018-01-16 02:33 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +### Certifcation? You want to see my certification?
Certification

2018-01-16 02:33 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +Once it arrives on Ted's doorstep, he will be able to unlock his own lock and have access to the letter, which tells Ted that he is _'totally awesome'_ and _'far out'_. He also now has a lock that he
**Song** and dance as before.

2018-01-16 02:33 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +Once it arrives on Ted's doorstep, he will be able to unlock his own lock and have access to the letter, which tells Ted that he is _'totally awesome'_ and _'far out'_. He also now has a lock that he
I guess this would complicate the diagram since your main intent is to show what is _locking_ the box and not what is _inside_ the box, but it would probably be helpful to add a little more explanation as to the contents of the box. You mention at the beginning of this section
>Bill also places another lock and a key, which he has his own copy of, inside the box.

and here that 
>He also now has a lock that he can use to send a response to Bill

I'm wondering what this lock and key is... are these the same as the impenetrable lock Bill uses _on_ the box?

2018-01-16 02:33 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +The aforementioned assymetric encryption is done through means of RSA, where a certificate, or "public key," is sent by the server to client when the client first reaches out. This public key is almo
spacing: `signing/issuing`

2018-01-16 02:33 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +Once this new MAC (message authentication code) is established via a so called "handshake," things get [a bit more complicated][tls_complications] as there are additional keys involved, but essential
`"handshake",`

2018-01-16 02:33 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> +Yes invisible. One of the most important parts of SSL/LTS is that the application layer, or HTTP layer, are all agnostic to this type of interaction. There is some overhead but it is fixed for symmet
I guess `is all` vs `are all` since the object in the sentence is singular?

2018-01-16 02:33 UTC, michaelkochub commented on _posts/2018-1-7-ssl-laymen.md
> + SSL/LTS is very important because for many internet based systems it is the only mechanism of transport encryption. Usage of older versions of the protocol are dangerous because they expose values t
Capitalize `java`

2018-01-16 04:12 UTC, mckornfield commented on _posts/2018-1-7-ssl-laymen.md
> +Once it arrives on Ted's doorstep, he will be able to unlock his own lock and have access to the letter, which tells Ted that he is _'totally awesome'_ and _'far out'_. He also now has a lock that he
I think my metaphor here is a bit mixed up, so I might cut it out. Honestly adding the lock inside does not really capture reality anyway. I will come up with something different.

2018-01-16 04:32 UTC, mckornfield commented
@michaelkochub I think I captured all your feedback. I decided to pull the lock IN the box out of the metaphor since I think it obfuscated the point (which was asymmetric encryption). Should be ready for another round

2018-01-19 01:17 UTC, michaelkochub approved these changes
You had `son and dance` and `certiicate is in the truststore` but all good, minor typos that I'll fix since I need to make some changes anyway to handle the new yaml metadata. Merging!

2018-01-19 01:18 UTC, merged

2018-01-19 02:25 UTC, mckornfield commented
Lol I could have sworn I fixed some of those but I must have overwritten myself X/ TY :)

2018-01-19 02:26 UTC, mckornfield commented
Yay 
![image](https://user-images.githubusercontent.com/16839335/35131790-329b1ac8-fc96-11e7-8f3a-d78d9638ee19.png)

:)

2018-01-19 02:28 UTC, michaelkochub commented
@mckornfield check again :wink: